apiVersion: v1
kind: Service
metadata:
  name: sentiment-svc
spec:
  selector:
    name: sentiment-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8001
    nodePort: 30001
  type: NodePort
